### PR TITLE
Add bigint to pushdown config

### PR DESCRIPTION
**Pull request by marklynch**
As part of https://github.com/EnterpriseDB/mysql_fdw/issues/266 there are missing values that can safely be pushed down - specifically all bigint values.

This adds the missing bigint comparison values so that out of the box the mysql_fdw is more functional across a wider range of data.

### CODE REVIEW

**Comment by marklynch** [comment]
@jeevanchalke would be great to get your eyes on this if you have a moment, as it's a small fix to the work you did here: https://github.com/EnterpriseDB/mysql_fdw/commit/f9f43d0c3566b2abc16a34b6830c49e2ce307df3

Thanks,
Mark

**Comment by surajkharage19** [comment]
Thanks @marklynch for your request.

The main purpose of configuration file is to provide a way for a user to decide which operators/function can be pushdown to the remote server. User can always modify that file as per their requirement. However, we are looking into your request and we will try to add commonly used operators as a default in that file.

**Comment by marklynch** [comment]
Thanks @surajkharage19.  Unfortunately this file is not modifiable when using on AWS RDS instances - so we've had to roll back to using the older version of mysql_fdw.

**Comment by marklynch** [comment]
Hi @surajkharage19, I've done some further testing on the older version 2.7.0 and ran into the data truncation issue that has been resolved in 2.9.0 version.  So I'm back on this version now.

I'm discussing with AWS at the moment on this - and wondering is there any chance of getting these fixes pushed into a 2.9.1 release - or is that a large effort?

**Comment by surajkharage19** [comment]
Hi @marklynch,

I don't think so these are large efforts, will try to get that in soon. Meanwhile if you could get access to the file then that would be great.

**Comment by surajkharage19** [comment]
Hi @marklynch,

We have now added more default entires in the configuration file which includes the entries suggested by you. Can you please check if that is useful at your end?

**Comment by marklynch** [comment]
@surajkharage19  - yes this looks really helpful.  I won't be able to test this in RDS sadly - as it won't get there until released - but I'll follow up with AWS support once it is released.

**Pull request closed without merging**
