### PR TITLE
Add support for binary / varbinary

### PR DESCRIPTION
**Pull request by rclmenezes**

### CODE REVIEW

**Comment by slava-pagerduty** [comment]
great! thank you very much!
sorry that I didn't get to do this myself, which I should..

**Comment by rclmenezes** [comment]
Hello! Any chance we can get this merged?

**Comment by krisnamourt** [comment]
Hi guys any news about it?

**Comment by surajkharage19** [comment]
Thanks for getting back on this. 
We will consider this request. Currently, the workaround is to create tables (that have binary/varbinary data type) manually using create foreign table command and use bytea type to map with binary/varbinary data type.

**Comment by krisnamourt** [comment]
Thanks for the feedback. I was imagined that I could create and map manually the columns, this answer another question, thanks!

**Comment by rclmenezes** [comment]
Seems like this was already added?
https://github.com/EnterpriseDB/mysql_fdw/commit/2b66862ac17b2ed82b03856c48dc7e3c3ad66470

Can close this ticket.

**Pull request closed without merging**
