### PR TITLE
Enable making SSL-secured connections to the MySQL server

### LINKED ISSUE #88: Support connecting to a MySQL server with SSL

### PR DESCRIPTION
**Pull request by blalor**
Fixes #88.  @saikat can you test this out, please?  The code compiles, but I don't have the ability to test it.

### CODE REVIEW

**Comment by saikat** [comment]
Will do shortly, thank you @blalor

**Comment by saikat** [comment]
@blalor Worked! Thank you so much, this is amazing.

**Comment by blalor** [comment]
Excellent!

**Comment by blalor** [comment]
Any feedback from the maintainers on this?

**Comment by ibrarahmad** [comment]
I will review that patch early next week and give my feedback.


On Fri, Feb 5, 2016 at 4:51 PM, Brian Lalor <notifications@github.com>
wrote:

> Any feedback from the maintainers on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/pull/89#issuecomment-180318203>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by blalor** [comment]
Thanks!

**Pull request merged**
