### PR TITLE
Refactor README.md for PGXN

### PR DESCRIPTION
**Pull request by mkgrgis**
For unifying with https://github.com/pgspider FDW documentation template and by https://github.com/ibarwick/firebird_fdw/blob/master/README.md example of advanced FDW documentation.

### CODE REVIEW

**Comment by mkgrgis** [comment]
Ping, my_sql FDW team ? Is the project still active? Are maintainers interesting in unified  `README.md` for PostgreSQL extension network (PGXN) ?

**Comment by surajkharage19** [comment]
Hi @mkgrgis,

Yes, this project is active. We will look into the README changes suggested by you.

Thanks.

**Comment by mkgrgis** [comment]
Hello, @surajkharage19 ! I am ready for review. Also I have similar PR for `mongo_fdw` https://github.com/EnterpriseDB/mongo_fdw/pull/168 , but this will also stopped without any comments.

**Comment by mkgrgis** [comment]
Hello, @surajkharage19! My MongoDB `README.md` refactoring was completely accepted in https://github.com/EnterpriseDB/mongo_fdw/commit/373ea031a0870d105e73c367fdf26fa35cafe797, let's continue our review?

**Comment by mkgrgis** [comment]
Ping, @surajkharage19 ! Most of other PostgreSQL FDWs yet use documentation structure from this PR: [EnterpriseDB mongo_fdw](https://github.com/EnterpriseDB/mongo_fdw), [redis_cluster_fdw](https://github.com/jeffreydwalter/redis_cluster_fdw), [sqlite_fdw](https://github.com/pgspider/sqlite_fdw), [firebird_fdw](https://github.com/ibarwick/firebird_fdw), [nfluxdb_fdw](https://github.com/pgspider/influxdb_fdw) etc. Why this review was stopped? I think `mysql_fdw` is very popular and provided by PGDG repository. Have my PR any problems?

**Comment by mkgrgis** [comment]
Ping @ALL, is this project still active? Does here reviews PRs at all?

**Comment by surajkharage19** [comment]
Hi @mkgrgis,

Sorry for the delay in reply. Thanks for submitting the pull request. We have committed this by making a few changes.

**Comment by mkgrgis** [comment]
Thanks, @surajkharage19. I'll made next PR about README some time later.

**Pull request closed without merging**
